manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: jakekausler
      url-base: https://github.com/jakekausler
  projects:
    - name: zmk
      remote: jakekausler
      revision: main
      import: app/west.yml
  self:
    path: config
